### ISSUE TITLE
Not working when `python-shell-interpreter` = `jupyter-console`

### ISSUE THREAD

**Issue by aiguofer** [proofit404/djangonaut#10]
Hey, I'm just trying your module as it seems quite promising, thanks for developing!

I prefer Jupyter console over the native Python shell, so I set my default shell in my init:

```lisp
  (setq python-shell-interpreter "jupyter-console"
        python-shell-interpreter-args "--simple-prompt"
        python-shell-prompt-detect-failure-warning nil)
```

Unfortunately, this seems to break all they `djangonaut-call`s. 

Looking around, I believe it's due to the `-c` that gets passed to `pythonic-call-process` since `jupyter-console` does not have such an option since it's meant to be more of a REPL than an interpreter.

I'm not sure that there's any straighforward solution... but here's some things that come to mind (and since I know you developed pythonic as well):

- Pythonic could just always use `python` instead of `python-shell-interpreter`, but this would be an issue for people setting `cython`, `jython`, or specifying between python2/3.
- Pythonic could have its own optional `interpreter` variable which would take precedence over `python-shell-interpreter` if set.

I kept trying to think of things that `djangonaut` could do different... but it would still be bound by the same problems.

Thoughts?

**Comment by proofit404** [comment]
Hi @aiguofer 

Thanks for trying `djangonaut`!

Yes, this is an old well-known problem in all `pythonic` based packages.

I think the only thing we could do is refactor pythonic to use its own variable for python executable.

Because supporting all possible interpreters to work in all pythonic based projects seems impossible to me.

Regards,
Artem.

**Comment by aiguofer** [comment]
This was fixed by https://github.com/proofit404/pythonic/pull/13
