### ISSUE TITLE
Handling info messages

### ISSUE THREAD

**Issue by olymk2** [proofit404/djangonaut#4]
Djangonaut is currently not working for me because the results of its internal command return info messages I am assuming.

Example output below

```
WARNING:googleads.common:Your default encoding, None, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.19.0.7
["check", "compilemessages", "createcachetable", "dbshell", "diffsettings", "dumpdata", "flush", "inspectdb", "loaddata", "makemessages", "makemigrations", "migrate", "runserver", "sendtestemail", "shell", "showmigrations", "sqlflush", "sqlmigrate", "sqlsequencereset", "squashmigrations", "startapp", "startproject", "test", "testserver", "admin_generator", "clean_pyc", "clear_cache", "compile_pyc", "create_app", "create_command", "create_jobs", "create_template_tags", "delete_squashed_migrations", "describe_form", "drop_test_database", "dumpscript", "export_emails", "find_template", "generate_secret_key", "graph_models", "mail_debug", "notes", "passwd", "pipchecker", "print_settings", "print_user_for_session", "reset_db", "runjob", "runjobs", "runprofileserver", "runscript", "runserver_plus", "set_default_site", "set_fake_emails", "set_fake_passwords", "shell_plus", "show_template_tags", "show_templatetags", "show_urls", "sqlcreate", "sqldiff", "sqldsn", "sync_s3", "syncdata", "unreferenced_files", "update_permissions", "validate_templates", "debugsqlshell", "clear_campaigns", "populate_campaigns", "populate_conversions", "spreadsheet_update_campaign_data", "spreadsheet_update_conversion_data", "account_unsetmultipleprimaryemails", "collectstatic", "findstatic", "clearsessions", "remove_stale_contenttypes", "changepassword", "createsuperuser"]
```

Could this be handled, or could there be some info on how to test the container outside of djangonaut when i exec or use run in a container I do not see these issues so assume it something about the command that djangonaut is sending, is there a verbose mode perhaps ?

**Comment by proofit404** [comment]
Is there a way in python I can suppress all logging messages? Have no time to research myself.

**Comment by olymk2** [comment]
well possibly in a way I need the exact command thats being run to diagnose, if i go direct to the container I dont get these log messages so some environment variable is likely different was hoping there was a way to show some verbose info / the commands being used under the hood to debug.

**Comment by proofit404** [comment]
First of all, it's two commands which try to figure out if you are in the Django project or not.
- djangonaut-get-project-root-code
- djangonaut-get-pythonpath-code

If those commands were successful, you will see Djangonaut mode activated in the current buffer. Then it will try to run command related code. For example, 
- djangonaut-get-models-code
- djangonaut-get-views-code

You can inspect this variables values with `C-h v` key binding, copy the value with double quotes and then use it with `python -c` command in your shell.

Output should be json parsable.
