### ISSUE TITLE
Mutiple virtualenvs?

### ISSUE THREAD

**Issue by alastairdb** [proofit404/djangonaut#8]
Am I correct in assuming you can work with multiple virtualenvs in djangonaut if you keep switching between them with `pythonic-acitivate`? In other situations, I have managed to work with several virtualenvs by setting `python-shell-virtualenv-root` in `.dir-locals.el`. But I think it was a design decision of djangonaut not to support this approach. In any event, the local variables approach hits problems in `djangonaut-call`, which uses `with-output-to-string`. This executes pythonic code in a new `*string-output*` buffer and the connection between pythonic and buffer local variables is lost.

**Comment by proofit404** [comment]
Hi,

Pythonic activate basically just set virtual environment root.

Djangonaut was designed with flexibility in mind. It should support different virtual environments on per buffer basis. Dir locals should be supported.

If you have any problems with multiple environments please report it.

Regards, Artem.

**Comment by alastairdb** [comment]
I finally figured this out. I will document my discovery here in case someone (like me in a couple of months) is Googling for a solution. The basic form of the `.dir-locals.el` file should be as follows:
``` elisp
((nil
  (python-shell-process-environment . ("DJANGO_SETTINGS_MODULE=fooproject.settings"))
  (python-shell-extra-pythonpaths . ("/home/foouser/Dev/fooproject/fooproject"))
  (python-shell-virtualenv-root . "/home/foouser/Dev/fooproject/.venv")))
```
Crucially, restricting the scope of the variables to `python-mode` does not work. You have to use `nil` for the scope. This is because djangonaut calls `hack-dir-local-variables` when it is in a temporary buffer, not the buffer of the Python source code.

**Comment by proofit404** [comment]
Thanks for the explanation! Can you form it into PR, so it became part of the docs? I think the FAQ section will be a great candidate for it.

**Comment by alastairdb** [comment]
I couldn't find a  FAQ. I added another section to the configuration info in the main README

**Comment by proofit404** [comment]
That should work, thanks!
